## 任务1：pytorch张量计算与numpy的转换

In [1]:
import numpy as np
import torch

c = np.ones((3, 3))
d = torch.from_numpy(c) # numpy 转 tensor
print(c)
print("--------------------")
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
--------------------
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
