## 任务2：梯度计算和梯度下降过程

In [5]:
import numpy as np
import torch
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

x_train = np.arange(0, 100, 0.01, dtype=np.float)
x_train = x_train.reshape(x_train.shape[0], 1)
y_train = 10 * x_train + 4 + np.random.randn()
x_train = torch.from_numpy(x_train)
y_train = torch.from_numpy(y_train)
dataset = TensorDataset(x_train, y_train)
batch_size = 100
train_loader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

w = torch.randn(1, requires_grad=True, dtype=torch.float64)
b = torch.randn(1, requires_grad=True, dtype=torch.float64)

In [7]:
epochs =500
learning_rate = 1e-4
loss_func = torch.nn.MSELoss()
for i in range(epochs):
    for inp, target in train_loader:
        z = torch.matmul(inp, w) + b
        z = z.reshape(z.shape[0], 1)
        loss = loss_func(z, target)
        loss.backward()
        with torch.no_grad():
            w -= learning_rate * w.grad
            b -= learning_rate * b.grad
            w.grad.zero_()
            b.grad.zero_()
    
    if i % 10 == 0:
        print(i, loss)

0 tensor(0.8434, dtype=torch.float64, grad_fn=<MseLossBackward>)
10 tensor(0.6927, dtype=torch.float64, grad_fn=<MseLossBackward>)
20 tensor(0.6798, dtype=torch.float64, grad_fn=<MseLossBackward>)
30 tensor(0.4682, dtype=torch.float64, grad_fn=<MseLossBackward>)
40 tensor(0.3755, dtype=torch.float64, grad_fn=<MseLossBackward>)
50 tensor(0.4239, dtype=torch.float64, grad_fn=<MseLossBackward>)
60 tensor(0.4943, dtype=torch.float64, grad_fn=<MseLossBackward>)
70 tensor(0.3490, dtype=torch.float64, grad_fn=<MseLossBackward>)
80 tensor(0.3445, dtype=torch.float64, grad_fn=<MseLossBackward>)
90 tensor(0.2473, dtype=torch.float64, grad_fn=<MseLossBackward>)
100 tensor(0.2424, dtype=torch.float64, grad_fn=<MseLossBackward>)
110 tensor(0.2542, dtype=torch.float64, grad_fn=<MseLossBackward>)
120 tensor(0.2165, dtype=torch.float64, grad_fn=<MseLossBackward>)
130 tensor(0.2082, dtype=torch.float64, grad_fn=<MseLossBackward>)
140 tensor(0.1928, dtype=torch.float64, grad_fn=<MseLossBackward>)
150 te

In [3]:
w

tensor([10.0072], dtype=torch.float64, requires_grad=True)

In [4]:
b

tensor([6.4750], dtype=torch.float64, requires_grad=True)

y = 10.0056 * x + 3.9470

In [21]:
x_train[1:10]

tensor([[0.0100],
        [0.0200],
        [0.0300],
        [0.0400],
        [0.0500],
        [0.0600],
        [0.0700],
        [0.0800],
        [0.0900]], dtype=torch.float64)

In [22]:
y_train[1:10]

tensor([[4.4201],
        [4.5201],
        [4.6201],
        [4.7201],
        [4.8201],
        [4.9201],
        [5.0201],
        [5.1201],
        [5.2201]], dtype=torch.float64)

In [23]:
y_pred = 10.0056 * x_train[1:10] + 3.9470
y_pred

tensor([[4.0471],
        [4.1471],
        [4.2472],
        [4.3472],
        [4.4473],
        [4.5473],
        [4.6474],
        [4.7474],
        [4.8475]], dtype=torch.float64)