### 基础pytorch教程
https://zhuanlan.zhihu.com/p/25572330

PyTorch是什么？是一个基于Python的科学计算包，有俩作用：
- 替代numpy发挥GPU潜能
- 一个提供了高度灵活性和效率的深度学习实验性平台

Tensors 和 numpy中的ndarrays相似：

## 官方教程
https://pytorch.org/tutorials/beginner/basics/intro.html

In [2]:
import torch
import numpy as np

In [4]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [6]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [9]:
x_ones = torch.ones_like(x_data)
print(x_ones)

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.1975, 0.2887],
        [0.5727, 0.0723]])


In [11]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
one_tensor = torch.ones(shape)
zero_tensor = torch.zeros(shape)

print(rand_tensor)
print(one_tensor)
print(zero_tensor)

tensor([[0.1959, 0.4348, 0.1017],
        [0.7396, 0.4397, 0.1796]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [12]:
tensor = torch.rand(3, 4)

In [13]:
tensor.shape

torch.Size([3, 4])

In [14]:
tensor.dtype

torch.float32

In [15]:
tensor.device

device(type='cpu')

In [16]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [17]:
tensor = torch.ones(4, 4)

In [18]:
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
tensor[0]

tensor([1., 1., 1., 1.])

In [20]:
tensor[:, 0]

tensor([1., 1., 1., 1.])

In [24]:
tensor[..., -1]

tensor([1., 1., 1., 1.])

In [22]:
tensor[:, 1] = 0

In [23]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [25]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)

In [26]:
t1

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

In [27]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [28]:
y1 = tensor @ tensor.T

In [29]:
y1

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [31]:
y2 = tensor.matmul(tensor.T)

In [32]:
y2

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [34]:
y3 = torch.rand_like(tensor)

In [35]:
torch.matmul(tensor, tensor.T, out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [36]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [37]:
z1 = tensor * tensor

In [38]:
z1

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [39]:
z2 = tensor.mul(tensor)

In [40]:
z2

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [43]:
z3 = torch.rand_like(tensor)

In [44]:
z3

tensor([[0.7488, 0.9114, 0.8759, 0.0735],
        [0.2203, 0.8614, 0.4617, 0.2505],
        [0.7817, 0.7632, 0.2328, 0.6592],
        [0.0456, 0.0989, 0.7284, 0.4716]])

In [45]:
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [46]:
agg = tensor.sum()

In [47]:
agg

tensor(12.)

In [48]:
agg.item()

12.0

In [53]:
type(agg)

torch.Tensor

In [54]:
t = torch.tensor([1, 2, 3])

In [55]:
t

tensor([1, 2, 3])

In [56]:
n = t.numpy()

In [57]:
n

array([1, 2, 3])

In [58]:
t.add_(1)

tensor([2, 3, 4])

In [59]:
t

tensor([2, 3, 4])

In [60]:
n

array([2, 3, 4])

In [61]:
n = np.ones(5)

In [62]:
n

array([1., 1., 1., 1., 1.])

In [64]:
t = torch.from_numpy(n)

In [65]:
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [67]:
np.add(n, 1, out=n)

array([2., 2., 2., 2., 2.])

In [68]:
n

array([2., 2., 2., 2., 2.])

In [69]:
t

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)